//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwIdentifier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mwIdentifier.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Done.
        /// </summary>
        internal static string msgDone_Text {
            get {
                return ResourceManager.GetString("msgDone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a layer to identify features in..
        /// </summary>
        internal static string msgIdentFromNotSelected_Text {
            get {
                return ResourceManager.GetString("msgIdentFromNotSelected.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a layer to identify features with..
        /// </summary>
        internal static string msgIdentWithNotSelected_Text {
            get {
                return ResourceManager.GetString("msgIdentWithNotSelected.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No grid values fall within the selected shape(s)..
        /// </summary>
        internal static string msgNoGridValues_Text {
            get {
                return ResourceManager.GetString("msgNoGridValues.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select Shapes.
        /// </summary>
        internal static string msgSelectShapes_Text {
            get {
                return ResourceManager.GetString("msgSelectShapes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Shapes Selected).
        /// </summary>
        internal static string msgShapesSelected_Text {
            get {
                return ResourceManager.GetString("msgShapesSelected.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one shape to identify against..
        /// </summary>
        internal static string msgZeroShapesSelected_Text {
            get {
                return ResourceManager.GetString("msgZeroShapesSelected.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string mwIdentifier_Name {
            get {
                return ResourceManager.GetString("mwIdentifier.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Grid Values.
        /// </summary>
        internal static string titleNoGridValues_Text {
            get {
                return ResourceManager.GetString("titleNoGridValues.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Shapes.
        /// </summary>
        internal static string titleSelectShapes_Text {
            get {
                return ResourceManager.GetString("titleSelectShapes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Layer.
        /// </summary>
        internal static string titleSpecifyLayer_Text {
            get {
                return ResourceManager.GetString("titleSpecifyLayer.Text", resourceCulture);
            }
        }
    }
}
