'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resource
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GISTools.Resource", GetType(Resource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Centimeters.
        '''</summary>
        Friend ReadOnly Property cmbMapUnit_Items() As String
            Get
                Return ResourceManager.GetString("cmbMapUnit.Items", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DecimalDegrees.
        '''</summary>
        Friend ReadOnly Property cmbMapUnit_Items1() As String
            Get
                Return ResourceManager.GetString("cmbMapUnit.Items1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Feet.
        '''</summary>
        Friend ReadOnly Property cmbMapUnit_Items2() As String
            Get
                Return ResourceManager.GetString("cmbMapUnit.Items2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inches.
        '''</summary>
        Friend ReadOnly Property cmbMapUnit_Items3() As String
            Get
                Return ResourceManager.GetString("cmbMapUnit.Items3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kilometers.
        '''</summary>
        Friend ReadOnly Property cmbMapUnit_Items4() As String
            Get
                Return ResourceManager.GetString("cmbMapUnit.Items4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Meters.
        '''</summary>
        Friend ReadOnly Property cmbMapUnit_Items5() As String
            Get
                Return ResourceManager.GetString("cmbMapUnit.Items5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Miles.
        '''</summary>
        Friend ReadOnly Property cmbMapUnit_Items6() As String
            Get
                Return ResourceManager.GetString("cmbMapUnit.Items6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Millimeters.
        '''</summary>
        Friend ReadOnly Property cmbMapUnit_Items7() As String
            Get
                Return ResourceManager.GetString("cmbMapUnit.Items7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yards.
        '''</summary>
        Friend ReadOnly Property cmbMapUnit_Items8() As String
            Get
                Return ResourceManager.GetString("cmbMapUnit.Items8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3D vector to 2D vector.
        '''</summary>
        Friend ReadOnly Property mnu3Dto2D_Text() As String
            Get
                Return ResourceManager.GetString("mnu3Dto2D.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aggregate shapes.
        '''</summary>
        Friend ReadOnly Property mnuAggregateShapes_Text() As String
            Get
                Return ResourceManager.GetString("mnuAggregateShapes.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assign Projection to Grids.
        '''</summary>
        Friend ReadOnly Property mnuApplyProjGRID_Text() As String
            Get
                Return ResourceManager.GetString("mnuApplyProjGRID.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assign Projection to Images.
        '''</summary>
        Friend ReadOnly Property mnuApplyProjImage_Text() As String
            Get
                Return ResourceManager.GetString("mnuApplyProjImage.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assign Projection to Shapefile.
        '''</summary>
        Friend ReadOnly Property mnuApplyProjSF_Text() As String
            Get
                Return ResourceManager.GetString("mnuApplyProjSF.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attribute Query.
        '''</summary>
        Friend ReadOnly Property mnuAttributeQuery_Text() As String
            Get
                Return ResourceManager.GetString("mnuAttributeQuery.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buffer Shapes.
        '''</summary>
        Friend ReadOnly Property mnuBuffer_Text() As String
            Get
                Return ResourceManager.GetString("mnuBuffer.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buffer Shapes.
        '''</summary>
        Friend ReadOnly Property mnuBufferNew_Text() As String
            Get
                Return ResourceManager.GetString("mnuBufferNew.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculate Polygon Areas.
        '''</summary>
        Friend ReadOnly Property mnuCalculateArea_Text() As String
            Get
                Return ResourceManager.GetString("mnuCalculateArea.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Grid Formats.
        '''</summary>
        Friend ReadOnly Property mnuChangeFormatGRID_Text() As String
            Get
                Return ResourceManager.GetString("mnuChangeFormatGRID.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Nodata Value.
        '''</summary>
        Friend ReadOnly Property mnuChangeNodata_Text() As String
            Get
                Return ResourceManager.GetString("mnuChangeNodata.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clip Grid With Polygon.
        '''</summary>
        Friend ReadOnly Property mnuClipGridWithPoly_Text() As String
            Get
                Return ResourceManager.GetString("mnuClipGridWithPoly.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clip Polygon with Line.
        '''</summary>
        Friend ReadOnly Property mnuClipPolyWithLine_Text() As String
            Get
                Return ResourceManager.GetString("mnuClipPolyWithLine.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clip Shapefile With Polygon.
        '''</summary>
        Friend ReadOnly Property mnuClipSFWithPoly_Text() As String
            Get
                Return ResourceManager.GetString("mnuClipSFWithPoly.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generate a Contour Shapefile.
        '''</summary>
        Friend ReadOnly Property mnuContour_Text() As String
            Get
                Return ResourceManager.GetString("mnuContour.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create Grid Images.
        '''</summary>
        Friend ReadOnly Property mnuCreateImageGRID_Text() As String
            Get
                Return ResourceManager.GetString("mnuCreateImageGRID.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Tools.
        '''</summary>
        Friend ReadOnly Property mnuDatabaseTools_Text() As String
            Get
                Return ResourceManager.GetString("mnuDatabaseTools.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dissolve by Attribute.
        '''</summary>
        Friend ReadOnly Property mnuDissolveByAttribute_Text() As String
            Get
                Return ResourceManager.GetString("mnuDissolveByAttribute.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erase Shapefile With Polygon.
        '''</summary>
        Friend ReadOnly Property mnuEraseSFWithPoly_Text() As String
            Get
                Return ResourceManager.GetString("mnuEraseSFWithPoly.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explode Shapes.
        '''</summary>
        Friend ReadOnly Property mnuExplodeShapes_Text() As String
            Get
                Return ResourceManager.GetString("mnuExplodeShapes.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Shapes to New Shapefile by Mask.
        '''</summary>
        Friend ReadOnly Property mnuExportByMask_Text() As String
            Get
                Return ResourceManager.GetString("mnuExportByMask.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Selection.
        '''</summary>
        Friend ReadOnly Property mnuExportSelected_Text() As String
            Get
                Return ResourceManager.GetString("mnuExportSelected.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fix up Shapefile.
        '''</summary>
        Friend ReadOnly Property mnuFixupShapefile_Text() As String
            Get
                Return ResourceManager.GetString("mnuFixupShapefile.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Georeference an Image or Grid.
        '''</summary>
        Friend ReadOnly Property mnuGeoreference_Text() As String
            Get
                Return ResourceManager.GetString("mnuGeoreference.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GIS Tools.
        '''</summary>
        Friend ReadOnly Property mnuGISTools_Text() As String
            Get
                Return ResourceManager.GetString("mnuGISTools.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Identify Shapes with Polygon.
        '''</summary>
        Friend ReadOnly Property mnuIdentity_Text() As String
            Get
                Return ResourceManager.GetString("mnuIdentity.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image Operations.
        '''</summary>
        Friend ReadOnly Property mnuImage_Text() As String
            Get
                Return ResourceManager.GetString("mnuImage.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import Shapefiles.
        '''</summary>
        Friend ReadOnly Property mnuLoadTable_Text() As String
            Get
                Return ResourceManager.GetString("mnuLoadTable.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge Shapes.
        '''</summary>
        Friend ReadOnly Property mnuMerge_Text() As String
            Get
                Return ResourceManager.GetString("mnuMerge.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge Grids.
        '''</summary>
        Friend ReadOnly Property mnuMergeGRIDS_Text() As String
            Get
                Return ResourceManager.GetString("mnuMergeGRIDS.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge Shapefiles.
        '''</summary>
        Friend ReadOnly Property mnuMergeNew_Text() As String
            Get
                Return ResourceManager.GetString("mnuMergeNew.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge Shapefiles.
        '''</summary>
        Friend ReadOnly Property mnuMergeSF_Text() As String
            Get
                Return ResourceManager.GetString("mnuMergeSF.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Identify Projection.
        '''</summary>
        Friend ReadOnly Property mnuProjectionIdentify_Text() As String
            Get
                Return ResourceManager.GetString("mnuProjectionIdentify.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Projection Viewer.
        '''</summary>
        Friend ReadOnly Property mnuProjectionManager_Text() As String
            Get
                Return ResourceManager.GetString("mnuProjectionManager.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raster.
        '''</summary>
        Friend ReadOnly Property mnuRaster_Text() As String
            Get
                Return ResourceManager.GetString("mnuRaster.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rectify Image to Worldfile.
        '''</summary>
        Friend ReadOnly Property mnuRectifyToWorldfile_Text() As String
            Get
                Return ResourceManager.GetString("mnuRectifyToWorldfile.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reproject Grids.
        '''</summary>
        Friend ReadOnly Property mnuReProjGRID_Text() As String
            Get
                Return ResourceManager.GetString("mnuReProjGRID.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reproject Images.
        '''</summary>
        Friend ReadOnly Property mnuReProjImage_Text() As String
            Get
                Return ResourceManager.GetString("mnuReProjImage.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reproject Shapefile.
        '''</summary>
        Friend ReadOnly Property mnuReProjSF_Text() As String
            Get
                Return ResourceManager.GetString("mnuReProjSF.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resample Grids.
        '''</summary>
        Friend ReadOnly Property mnuResampleGRID_Text() As String
            Get
                Return ResourceManager.GetString("mnuResampleGRID.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Shapefiles.
        '''</summary>
        Friend ReadOnly Property mnuSaveTable_Text() As String
            Get
                Return ResourceManager.GetString("mnuSaveTable.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clipping.
        '''</summary>
        Friend ReadOnly Property mnuSfClip_Text() As String
            Get
                Return ResourceManager.GetString("mnuSfClip.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Difference.
        '''</summary>
        Friend ReadOnly Property mnuSfDifference_Text() As String
            Get
                Return ResourceManager.GetString("mnuSfDifference.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Intersection.
        '''</summary>
        Friend ReadOnly Property mnuSfIntersection_Text() As String
            Get
                Return ResourceManager.GetString("mnuSfIntersection.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Symmetrical difference.
        '''</summary>
        Friend ReadOnly Property mnuSfSymmDifference_Text() As String
            Get
                Return ResourceManager.GetString("mnuSfSymmDifference.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Union.
        '''</summary>
        Friend ReadOnly Property mnuSfUnion_Text() As String
            Get
                Return ResourceManager.GetString("mnuSfUnion.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create Centroids.
        '''</summary>
        Friend ReadOnly Property mnuShapefileCentroids_Text() As String
            Get
                Return ResourceManager.GetString("mnuShapefileCentroids.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validate Shapefile.
        '''</summary>
        Friend ReadOnly Property mnuShapefileValidate_Text() As String
            Get
                Return ResourceManager.GetString("mnuShapefileValidate.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Simplify Lines.
        '''</summary>
        Friend ReadOnly Property mnuSimplifyLines_Text() As String
            Get
                Return ResourceManager.GetString("mnuSimplifyLines.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort Shapefile.
        '''</summary>
        Friend ReadOnly Property mnuSortShapefile_Text() As String
            Get
                Return ResourceManager.GetString("mnuSortShapefile.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spatial Query.
        '''</summary>
        Friend ReadOnly Property mnuSpatialQuery_Text() As String
            Get
                Return ResourceManager.GetString("mnuSpatialQuery.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vector Operations.
        '''</summary>
        Friend ReadOnly Property mnuVector_Text() As String
            Get
                Return ResourceManager.GetString("mnuVector.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculate.
        '''</summary>
        Friend ReadOnly Property mnuVectorCalculate_Text() As String
            Get
                Return ResourceManager.GetString("mnuVectorCalculate.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generilize.
        '''</summary>
        Friend ReadOnly Property mnuVectorGeneralize_Text() As String
            Get
                Return ResourceManager.GetString("mnuVectorGeneralize.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generate.
        '''</summary>
        Friend ReadOnly Property mnuVectorGenerate_Text() As String
            Get
                Return ResourceManager.GetString("mnuVectorGenerate.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modify.
        '''</summary>
        Friend ReadOnly Property mnuVectorModify_Text() As String
            Get
                Return ResourceManager.GetString("mnuVectorModify.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New vector tools.
        '''</summary>
        Friend ReadOnly Property mnuVectorNew_Text() As String
            Get
                Return ResourceManager.GetString("mnuVectorNew.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old tools.
        '''</summary>
        Friend ReadOnly Property mnuVectorOld_Text() As String
            Get
                Return ResourceManager.GetString("mnuVectorOld.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overlays.
        '''</summary>
        Friend ReadOnly Property mnuVectorOverlays_Text() As String
            Get
                Return ResourceManager.GetString("mnuVectorOverlays.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Projections.
        '''</summary>
        Friend ReadOnly Property mnuVectorProjections_Text() As String
            Get
                Return ResourceManager.GetString("mnuVectorProjections.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Query.
        '''</summary>
        Friend ReadOnly Property mnuVectorQuery_Text() As String
            Get
                Return ResourceManager.GetString("mnuVectorQuery.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Standard.
        '''</summary>
        Friend ReadOnly Property mnuVectorStandard_Text() As String
            Get
                Return ResourceManager.GetString("mnuVectorStandard.Text", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
