//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapWinGeoProc.clsUtils {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class ManhattanShapes {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ManhattanShapes() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapWinGeoProc.clsUtils.ManhattanShapes", typeof(ManhattanShapes).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Invalid shape generated.
		/// </summary>
		internal static string invalidshape {
			get {
				return ResourceManager.GetString("invalidshape", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cannot add field to shapefile .
		/// </summary>
		internal static string noaddfield {
			get {
				return ResourceManager.GetString("noaddfield", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cannot add shape to shapefile .
		/// </summary>
		internal static string noaddshape {
			get {
				return ResourceManager.GetString("noaddshape", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cannot close shapefile .
		/// </summary>
		internal static string nocloseshapefile {
			get {
				return ResourceManager.GetString("nocloseshapefile", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cannot create shapefile .
		/// </summary>
		internal static string nocreateshapefile {
			get {
				return ResourceManager.GetString("nocreateshapefile", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cannot edit cell in shapefile .
		/// </summary>
		internal static string noeditcell {
			get {
				return ResourceManager.GetString("noeditcell", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cannot edit shapefile .
		/// </summary>
		internal static string noeditshapefile {
			get {
				return ResourceManager.GetString("noeditshapefile", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cannot find grid .
		/// </summary>
		internal static string nogrid {
			get {
				return ResourceManager.GetString("nogrid", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cannot open grid .
		/// </summary>
		internal static string noopengrid {
			get {
				return ResourceManager.GetString("noopengrid", resourceCulture);
			}
		}
	}
}
